spring:
  application:
    name: crud

  datasource:
    url: jdbc:h2:mem:h2db; #DB_CLOSE_DELAY=-1 # Kết nối đến H2, DB_CLOSE_DELAY=-1 giữ cho database còn tồn tại đến khi JVM tắt, tránh việc H2 tự động đóng khi không còn kết nối.
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # Cho phép bật console.
      path: /h2-console # Mở H2 với đường dẫn http://localhost:<port>/h2/console.

  jpa:
    show-sql: true
    hibernate:
      dll-auto: create # Không hibernate tự động tạo schema/table từ entity. Các giá trị khác: create, update, validate, create-drop.

server:
  port: 8989
