
CREATE TABLE COURSES
(
    ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    RATING INT NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    PRIMARY KEY (ID)
);
